const projects = [

    {id: "1",
    name: "Drum Kit",
    image: "https://i.ibb.co/YLYch6y/drums.jpg",
    alt: "drums", 
    link: "https://olhakrasnokutska.github.io/drums/",
    },
    {id: "2",
    name: "About me page",
    image: "https://i.ibb.co/fNJrDbg/about-me.jpg",
    alt: "about-me",
    link: "https://olhakrasnokutska.github.io/About-me/",
    },
    {id: "3",
    name: "React Weather App",
    image: "https://i.ibb.co/db9W3rm/react-weather.jpg",
    alt: "react-weather",
    link: "https://exquisite-lily-17e1d1.netlify.app/",
    },
    {id: "4",
    name: "React Dictionary App",
    image: "https://i.ibb.co/93DpCPM/react-dictionary.jpg",
    alt: "react-dictionary",
    link: "https://serene-trifle-1e6c21.netlify.app/",
    },
    {id: "5",
    name: "Responsive Page",
    image: "https://i.ibb.co/tY3Mz18/cruissant.jpg",
    alt: "cruissant",
    link: "https://olhakrasnokutska.github.io/Croissant/",
    },
    {id: "6",
    name: "Weather app",
    image: "https://i.ibb.co/6y5PZ6c/weather.jpg",
    alt: "weather",
    link: "https://olhakrasnokutska.github.io/My-weather-app/",
    },
    {id: "7",
    name: "Basic Website",
    image: "https://i.ibb.co/Yb3v570/shecodes-basic.jpg",
    alt: "shecodes-basic",
    link: "https://olhakrasnokutska.github.io/SheCodes-Basic-Task/",
    }
];

export default projects;