const projects = [

    {id: "1",
    name: "Drum Kit",
    image: "https://i.ibb.co/D18H7zV/drums.jpg",
    alt: "drums",
    link: "https://olhakrasnokutska.github.io/drums/",
    },
    {id: "2",
    name: "About me page",
    image: "https://i.ibb.co/zZtSpvP/About-me.png",
    link: "https://olhakrasnokutska.github.io/About-me/",
    },
    {id: "3",
    name: "React Weather App",
    image: "https://i.ibb.co/PDRj7Mc/SC-React-Weather.jpg",
    link: "https://exquisite-lily-17e1d1.netlify.app/",
    },
    {id: "4",
    name: "React Dictionary App",
    image: "https://i.ibb.co/PjKNy01/SC-React-Dictionary.jpg",
    link: "https://serene-trifle-1e6c21.netlify.app/",
    },
    {id: "5",
    name: "Responsive Page",
    image: "https://i.ibb.co/XVVbKbs/SC-Responsive-Croissant.jpg",
    link: "https://olhakrasnokutska.github.io/Croissant/",
    },
    {id: "6",
    name: "Weather app",
    image: "https://i.ibb.co/5YJyC08/SC-Plus-Weather.jpg",
    link: "https://olhakrasnokutska.github.io/My-weather-app/",
    },
    {id: "7",
    name: "Basic Website",
    image: "https://i.ibb.co/JBDrnxX/SC-Basic-Website.jpg",
    link: "https://olhakrasnokutska.github.io/SheCodes-Basic-Task/",
    }
];

export default projects;